# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-26 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20180625_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='users_wishes',
            field=models.ManyToManyField(related_name='other_people_wish', to='first_app.User'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_wish', to='first_app.User'),
        ),
    ]
