# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-26 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20180626_0756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish',
            old_name='user_id',
            new_name='created',
        ),
    ]
